# Generated by Django 3.2 on 2021-05-02 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_contato_mostar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='mostar',
            new_name='mostrar',
        ),
    ]
